import Head from 'next/head'
import Image from 'next/image'
import {Inter} from '@next/font/google'
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Logo from "../../public/pinterest_board_photo.png";

const inter = Inter({subsets: ['latin']})

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className="min-h-screen flex flex-col">
                <Header/>
                <main className="flex-1 bg-indigo-50 p-2 bg-black">
                    <div className="mb-20 text-center">
                        <Image src={Logo} alt={"Logo"} className="inline-block" width={500}/>
                    </div>
                </main>
                <Footer/>
            </div>
        </>
    )
}
